import type { PortableTextBlock } from "next-sanity";
import type { ArtImage, Artwork, CategoryRef, SiteSettings } from "./types";

// Тестовые данные, пока не подключён Sanity (NEXT_PUBLIC_SANITY_PROJECT_ID пуст).

const img = (name: string, width: number, height: number, alt: string): ArtImage => ({
  src: `/mock/${name}.svg`,
  width,
  height,
  alt,
});

let key = 0;
const text = (...paragraphs: string[]): PortableTextBlock[] =>
  paragraphs.map((t) => ({
    _type: "block",
    _key: `k${key++}`,
    style: "normal",
    markDefs: [],
    children: [{ _type: "span", _key: `s${key++}`, text: t, marks: [] }],
  }));

const paintings: CategoryRef = { title: "Картины", slug: "kartiny" };
const wool: CategoryRef = { title: "Изделия из шерсти", slug: "sherst" };
const other: CategoryRef = { title: "Другое творчество", slug: "drugoe" };

export const mockCategoryMeta: Record<string, { order: number; description: string }> = {
  [paintings.slug]: { order: 1, description: "Масло, акрил и акварель" },
  [wool.slug]: { order: 2, description: "Валяные панно, игрушки и украшения" },
  [other.slug]: { order: 3, description: "Керамика, открытки и всё остальное" },
};

export const mockArtworks: Artwork[] = [
  {
    id: "a1",
    title: "Утро на реке",
    slug: "utro-na-reke",
    category: paintings,
    images: [img("painting-1", 1200, 1500, "Утренний туман над рекой")],
    status: "available",
    price: 18000,
    featured: true,
    description: text(
      "Тихое летнее утро, когда туман ещё не ушёл с воды. Написана на пленэре за два сеанса.",
      "Картина оформлена в тонкую деревянную раму, готова к подвесу.",
    ),
    dimensions: "40 × 50 см",
    materials: "Холст, масло",
    year: 2025,
  },
  {
    id: "a2",
    title: "Морской ветер",
    slug: "morskoy-veter",
    category: paintings,
    images: [img("painting-2", 1500, 1100, "Море и облака")],
    status: "available",
    price: 24000,
    featured: true,
    description: text("Свежий ветер, бирюзовая вода и облака, бегущие к горизонту."),
    dimensions: "60 × 45 см",
    materials: "Холст, акрил",
    year: 2025,
  },
  {
    id: "a3",
    title: "Поле в июле",
    slug: "pole-v-iyule",
    category: paintings,
    images: [img("painting-3", 1200, 1200, "Золотое поле")],
    status: "sold",
    price: 15000,
    featured: false,
    description: text("Жаркий июльский полдень и золотое поле до самого леса."),
    dimensions: "50 × 50 см",
    materials: "Холст на подрамнике, масло",
    year: 2024,
  },
  {
    id: "a4",
    title: "Сумерки",
    slug: "sumerki",
    category: paintings,
    images: [img("painting-4", 1100, 1500, "Сиреневые сумерки")],
    status: "commission",
    price: null,
    featured: false,
    description: text("Сиреневый вечер над городом. Оригинал в частной коллекции — можно заказать работу в похожем настроении."),
    dimensions: "35 × 50 см",
    materials: "Бумага, акварель",
    year: 2024,
  },
  {
    id: "a5",
    title: "Дюны",
    slug: "dyuny",
    category: paintings,
    images: [
      img("painting-5", 1600, 1100, "Песчаные дюны на закате"),
      img("painting-5b", 1200, 1500, "Фрагмент картины «Дюны»"),
    ],
    status: "available",
    price: 32000,
    featured: true,
    description: text(
      "Большая работа с тёплой песочной палитрой. Фактурные мазки мастихином хорошо видны при боковом свете.",
    ),
    dimensions: "70 × 50 см",
    materials: "Холст, масло, мастихин",
    year: 2026,
  },
  {
    id: "a6",
    title: "Ягодный этюд",
    slug: "yagodnyy-etyud",
    category: paintings,
    images: [img("painting-6", 1200, 1600, "Этюд с ягодами")],
    status: "available",
    price: 9500,
    featured: false,
    description: text("Небольшой этюд — красиво смотрится на кухне или в паре с другой работой."),
    dimensions: "30 × 40 см",
    materials: "Картон, масло",
    year: 2026,
  },
  {
    id: "a7",
    title: "Шерстяная мандала",
    slug: "sherstyanaya-mandala",
    category: wool,
    images: [
      img("wool-1", 1200, 1200, "Круглое панно из войлока"),
      img("wool-1b", 1200, 1500, "Панно на стене"),
    ],
    status: "available",
    price: 7500,
    featured: true,
    description: text("Круглое панно в технике мокрого валяния из мериноса. Мягкое на ощупь, тёплое по цвету."),
    dimensions: "Ø 30 см",
    materials: "Шерсть мериноса, войлок",
    year: 2026,
  },
  {
    id: "a8",
    title: "Мох и камень",
    slug: "moh-i-kamen",
    category: wool,
    images: [img("wool-2", 1200, 1500, "Зелёное валяное панно")],
    status: "available",
    price: 6800,
    featured: false,
    description: text("Панно с объёмной фактурой, напоминающей лесной мох."),
    dimensions: "25 × 30 см",
    materials: "Шерсть, шёлк",
    year: 2025,
  },
  {
    id: "a9",
    title: "Ягодка",
    slug: "yagodka",
    category: wool,
    images: [img("wool-3", 1400, 1200, "Валяная игрушка")],
    status: "sold",
    price: 3500,
    featured: false,
    description: text("Маленькая валяная игрушка. Эта уже нашла хозяев, но можно заказать похожую."),
    dimensions: "12 см",
    materials: "Шерсть, сухое валяние",
    year: 2025,
  },
  {
    id: "a10",
    title: "Морская галька",
    slug: "morskaya-galka",
    category: wool,
    images: [img("wool-4", 1200, 1200, "Набор войлочных подставок")],
    status: "available",
    price: 3200,
    featured: true,
    description: text("Набор из шести войлочных подставок под чашки в морских оттенках."),
    dimensions: "Ø 10 см, 6 шт.",
    materials: "Шерсть, войлок",
    year: 2026,
  },
  {
    id: "a11",
    title: "Ваза «Песок»",
    slug: "vaza-pesok",
    category: other,
    images: [img("craft-1", 1200, 1500, "Керамическая ваза")],
    status: "available",
    price: 4500,
    featured: false,
    description: text("Ваза ручной лепки, покрыта матовой глазурью."),
    dimensions: "Высота 22 см",
    materials: "Керамика, глазурь",
    year: 2026,
  },
  {
    id: "a12",
    title: "Авторские открытки",
    slug: "avtorskie-otkrytki",
    category: other,
    images: [img("craft-2", 1200, 1200, "Набор открыток")],
    status: "custom",
    price: null,
    options: [
      { label: "5 штук", price: 900 },
      { label: "10 штук", price: 1600 },
      { label: "20 штук", price: 2900, image: img("craft-1", 1200, 1200, "Набор из 20 открыток") },
    ],
    optionsTitle: "Набор",
    featured: false,
    description: text("Открытки с репродукциями картин. Делаю наборы под заказ — к праздникам и для подарков."),
    dimensions: "10 × 15 см",
    materials: "Бумага",
  },
];

export const mockSettings: SiteSettings = {
  title: "Valeri",
  tagline: "Картины, войлок и другие вещи, сделанные руками",
  portrait: img("portrait", 1200, 1500, "Valeri в мастерской"),
  about: text(
    "Привет! Я Valeri, художница. Пишу маслом и акварелью, валяю из шерсти и иногда леплю из глины.",
    "Каждая работа существует в единственном экземпляре. Если понравилась проданная — напишите, сделаю похожую специально для вас.",
    "Отправляю по всей России. Работы бережно упаковываю, картины — в жёсткую коробку.",
  ),
  contacts: {
    telegram: "valeri_art_demo",
    whatsapp: "79990000000",
    instagram: "valeri_art_demo",
    email: "hello@example.com",
  },
};
